--- # this is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: install git software
      yum: name=git state=installed
    - name: install httpd software
      yum: pkg=httpd state=installed
