--- # This is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: install git software
      yum: name={{ item }} state=installed
      loop:
        - git
        - httpd
        - telnet
