--- # this is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: install softwares
      yum: name={{ item }} state=installed
      loop: 
        - git
        - httpd
        - telnet
