--- # This is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: yes
  tasks:
    - name: install git software
      yum: name=git state=installed
      when: ansible_os_family == "RedHat"
